import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ReactNode } from "react";
import Footer from "./_components/Footer";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type LayoutProps = {
    children: ReactNode;
};

export default function RootLayout({ children }: Readonly<LayoutProps>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={inter.className}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange>
                    <div className='min-h-screen flex flex-col max-w-[1400px] mx-auto '>
                        <Navbar />
                        <main className=' flex-1 flex flex-col'>{children}</main>
                        <Footer />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
